# Generated by Django 4.2.6 on 2023-10-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idusuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(max_length=50)),
                ('contrasenausuario', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bodegamp',
            fields=[
                ('idbodega', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('ubicacionbodega', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'bodegamp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calibre',
            fields=[
                ('idcalibre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desccalibre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'calibre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desccategoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rut', models.BigIntegerField(blank=True, null=True)),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidopat', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidomat', models.CharField(blank=True, max_length=50, null=True)),
                ('estadoactivo', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=300)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('correoelectronico', models.CharField(max_length=300)),
                ('contrasena', models.CharField(max_length=300)),
                ('identificadorempresa', models.CharField(blank=True, max_length=300, null=True)),
                ('razonsocial', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idcomuna', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('nombrecomuna', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('idusuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(max_length=50)),
                ('contrasenausuario', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'consultor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoClienteEx',
            fields=[
                ('idcontrato', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fechainiciocontrato', models.DateField()),
                ('fechaterminocontrato', models.DateField()),
            ],
            options={
                'db_table': 'contrato_cliente_ex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoTransporte',
            fields=[
                ('id_contrato', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('fechacontrato', models.DateField()),
            ],
            options={
                'db_table': 'contrato_transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadopago',
            fields=[
                ('idpago', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descestadopago', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'estadopago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadopedido',
            fields=[
                ('idestado', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('descripcionestado', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'estadopedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idmarca', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('descmarca', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idmodelo', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('descmodelo', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'modelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenTransporte',
            fields=[
                ('idordent', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descordent', models.CharField(max_length=200)),
                ('fechatransporte', models.DateField()),
                ('diasdespacho', models.BigIntegerField()),
                ('direccionorigen', models.CharField(max_length=300)),
                ('direcciondestino', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'orden_transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fechapago', models.DateField()),
                ('estadopago', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idpais', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombrepais', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parametricaproduc',
            fields=[
                ('idproduc', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('idcalibre', models.CharField(max_length=300)),
                ('pesoproducaprox', models.BigIntegerField()),
            ],
            options={
                'db_table': 'parametricaproduc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fechapedido', models.DateField()),
                ('totalpedido', models.BigIntegerField()),
                ('iva', models.DecimalField(decimal_places=9, max_digits=9)),
                ('comisionmaipogrande', models.DecimalField(decimal_places=9, max_digits=9)),
                ('totaltransporte', models.BigIntegerField()),
                ('totalfinal', models.BigIntegerField()),
                ('pesototalpedido', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=50)),
                ('descproducto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('rut', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidopat', models.CharField(max_length=50)),
                ('apellidomat', models.CharField(max_length=50)),
                ('estadoactivo', models.CharField(max_length=1)),
                ('fechanacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=300)),
                ('correoelectronico', models.CharField(max_length=300)),
                ('contrasena', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'productor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idregion', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('nombreregion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('idseguro', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('nombreaseguradora', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'seguro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocliente',
            fields=[
                ('idcliente', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('descripciontipo', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'tipocliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposeguro',
            fields=[
                ('primaseguro', models.BigIntegerField()),
                ('idtiposeguro', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tiposeguro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('patente', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('capacidadcarga', models.BigIntegerField()),
                ('frigorificotrans', models.CharField(max_length=1)),
                ('permisocirculacion', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('rut', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidopat', models.CharField(max_length=50)),
                ('apellidomat', models.CharField(max_length=50)),
                ('estadoactivo', models.CharField(max_length=1)),
                ('fechanacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=300)),
                ('correoelectronico', models.CharField(max_length=300)),
                ('contrasena', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'transportista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductorProducto',
            fields=[
                ('precio', models.BigIntegerField()),
                ('stock', models.BigIntegerField()),
                ('producto_idproducto', models.OneToOneField(db_column='producto_idproducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='FeriaVirtual.producto')),
                ('img', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'productor_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('cantidad', models.BigIntegerField()),
                ('idproducto', models.OneToOneField(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='FeriaVirtual.productorproducto')),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
    ]
