# Generated by Django 4.2.6 on 2023-10-27 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FeriaVirtual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id_subasta', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fechasubasta', models.DateField()),
                ('horainiciosubasta', models.DateTimeField()),
                ('horaterminosubasta', models.DateTimeField()),
                ('estadodelasubasta', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'subasta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfertarSubasta',
            fields=[
                ('montosubasta', models.BigIntegerField()),
                ('subasta_id_subasta', models.OneToOneField(db_column='subasta_id_subasta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='FeriaVirtual.subasta')),
            ],
            options={
                'db_table': 'ofertar_subasta',
                'managed': False,
            },
        ),
    ]
