# Generated by Django 4.2.6 on 2023-11-24 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FeriaVirtual', '0002_subasta_ofertarsubasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccion_nueva', models.CharField(max_length=300)),
                ('cliente_id_cliente', models.OneToOneField(db_column='cliente_id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='direccion_cliente', serialize=False, to='FeriaVirtual.cliente')),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaError',
            fields=[
                ('id_error', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('desc_errores', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'tabla_error',
                'managed': False,
            },
        ),
    ]
